### ISSUE TITLE
Feature request: provide 'location' as a second argument to parseQueryString and stringifyQuery

### ISSUE THREAD

**Issue by smashercosmo** [ReactJSTraining/history#303]
Because sometimes it is useful to handle query string differently, depending on the current location.

**Comment by taion** [comment]
Not a fan of this – this would create odd order-dependent semantics; the location doesn't exist at this point, and it's just bizarre for serialization/deserialization to depend on location.

**Comment by smashercosmo** [comment]
What do you mean by
> order-dependent semantics

and
> location doesn't exist at this point

'location' is passed to decodeQuery and encodeQuery functions https://github.com/ReactJSTraining/history/blob/master/modules/useQueries.js#L26-L36. Why not pass it further to stringifyQuery and parseQueryString?

**Comment by timdorr** [comment]
The "location descriptor" object doesn't exist at that point. `location` [can be null](https://github.com/ReactJSTraining/history/blob/master/modules/useQueries.js#L27) or [a string](https://github.com/ReactJSTraining/history/blob/master/modules/useQueries.js#L40), so the "location" being passed in isn't yet a normalized location descriptor that is used everywhere else.

Because we don't know its type, it's not a good idea to provide that to our APIs. It makes implementation messy and harder for users.
