### ISSUE TITLE
Prevent encoding `+` in query string

### ISSUE THREAD

**Issue by preflight** [ReactJSTraining/history#319]
I need to format a query string using `+` to indicate multiple values for a given property, such as:
`url.com?foo=bar+baz`

I'm calling `history.replace` (via react router) and assigning the formatted string as a value in the `query` object:

```
router.replace({
  pathname: '/users/12',
  query: { foo: "bar+baz" },
  state: null
});
```

Somewhere along the way to `window.history.replaceState`, the plus sign is being encoded as:
`/url.com?foo=bar%2Bbaz`

This appears to occur in [`useQueries.js`](https://github.com/ReactJSTraining/history/blob/master/modules/useQueries.js) or one of its imports/dependencies.

How can I prevent this encoding?

**Comment by taion** [comment]
`+` isn't a valid character in a query string. Use a space, or provide your own encoding/decoding functions.

**Comment by preflight** [comment]
Thanks for responding. Would I provide the encoding/decoding functions by using a [custom history](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#using-custom-histories)?

**Comment by taion** [comment]
If you're using React Router, yes.

**Comment by taion** [comment]
If you're using React Router, yes.

**Comment by preflight** [comment]
Thank you - issue can be closed.

**Comment by oyeanuj** [comment]
@taion It seems that this comment on a similar issue by @mjackson is saying otherwise - that `+` is a valid character in query strings.

https://github.com/ReactTraining/react-router/issues/716#issuecomment-71346876

According to that issue, it shouldn't be decoded and converted to space. Can you or @mjackson clarify and confirm the expected behavior?
